build: false
clone_folder: c:\projects\padawan

cache:
    - composer.phar

init:
    - SET PATH=c:\php;%PATH%
    - SET COMPOSER_NO_INTERACTION=1

install:
    - mkdir c:\php && cd c:\php
    - appveyor DownloadFile http://windows.php.net/downloads/releases/archives/php-5.5.9-nts-Win32-VC11-x86.zip
    - 7z x php-5.5.9-nts-Win32-VC11-x86.zip -y >nul
    - del /Q *.zip
    - copy /Y php.ini-development php.ini-min
    - echo max_execution_time=1200 >> php.ini-min
    - echo date.timezone="America/Los_Angeles" >> php.ini-min
    - echo extension_dir=ext >> php.ini-min
    - cd c:\projects\padawan
    - IF NOT EXIST composer.phar (appveyor DownloadFile https://getcomposer.org/download/1.3.0/composer.phar)
    - php composer.phar self-update
    - copy /Y .composer\* %APPDATA%\Composer\
    - php composer.phar install --no-progress --ansi

test_script:
    - cd c:\projects\padawan
    - SET X=0
    - php bin/peridot specs || SET X=!errorlevel!
    - php bin/behat || SET X=!errorlevel!
    - exit %X%
